rancher/image-build-calico

Dockerfile

This changes kube-proxy to use the iptables provided by k3s-root (1.8.3) rather than using the ubi7 provided iptables. This allows for switching between nft and legacy on the fly.
https://github.com/rancher/rke2/issues/16
Signed-off-by: Chris Kim <oats87g@gmail.com>

Update to use k3s-root v0.6.0-rc3 xtables autodetection

---

.drone.yml
Dockerfile
Makefile

Signed-off-by: Brad Davidson <brad.davidson@rancher.com>

bump golang and package versions

---

Dockerfile

Signed-off-by: Brad Davidson <brad.davidson@rancher.com>

Bump CNI plugins source image

---

Dockerfile
Makefile

Signed-off-by: Manuel Buil <mbuil@suse.com>

Update base image

---

Dockerfile

Signed-off-by: Brad Davidson <brad.davidson@rancher.com>

Bump cni-plugins and k3s-root

---

Dockerfile
Makefile
README.md

Update calico to version 3.21.4 updating the used git repository (#17)

Update calico 3.21.4

---

Dockerfile

Signed-off-by: manuelbuil <mbuil@suse.com>

Add kube-controller to canal image

---

Dockerfile

Fix DualStack patch v3.21.4

---

Dockerfile
Makefile
README.md

Updated to v3.22.0

---

Dockerfile
Makefile

Signed-off-by: Manuel Buil <mbuil@suse.com>

Update calico to 3.22.2 and K3S_ROOT_VERSION

---

Dockerfile
Makefile
README.md

Updated Calico to v3.23.3

---

Dockerfile
Makefile
README.md

Update Calico version to 3.24.1

Update calico to 3.24.1

---

Dockerfile

Issue: https://github.com/rancher/rke2/issues/3424
var expansion does not work as in shell when using docker run. Therefore, we can't just add the variable before the command to be run.
This PR fixes that and now calico-node uses the LDFLAGS correctly and for example, shows the version
Signed-off-by: Manuel Buil <mbuil@suse.com>

Fix calico build

---

Dockerfile
Makefile
README.md

Update calico to v3.24.5

---

Dockerfile
Makefile
README.md

Update Calico version to 3.25.0

---

Dockerfile
Makefile
README.md

Update calico version to v3.26.1.

Update Calico to v3.26.1

---

Dockerfile
Makefile

Update calico to version 3.27.0

---

.github/workflows/image-push.yml
Dockerfile

No need to use TargetArch here since we are using hosted runners, the fix however will pass the ARCH value that is being fetched in the Makefile

Fix Architecture

---

Dockerfile

Update go version base image

---

.github/workflows/image-push.yml
Dockerfile
Makefile

- fixes use of ARCH arg
- manifest-push writes multi-arch index digest to file for image signing

fix cross-platform builds, multi-arch signing

---

.github/workflows/release.yml
Makefile

This should add multiple source when the manifest is built.

Fixed arm64 push images

---

Makefile

This PR fixes the Makefile script to extract the digest.

Fixed Makefile to build multiple arch

---

Makefile

[LTS] Add SRC tag

---

Dockerfile

This PR adds the libbpf library to the source before the build. From Calico v3.30 the source for libbpf was removed.

Added libbpf download before build
