.drone.yml
Dockerfile
Makefile

Leverage new alpine-based rancher/hardened-build-base (goboring built on
alpine) while matching the upstream version of go to compile with. Also
assert everything is statically linked and assert presence of goboring
symbols prior to install-with-strip.
Addresses rancher/rke2#335

statically linked calico

---

Dockerfile
Makefile
dualStack-changes.patch

Updates to version v3.20.3 of calico and latest on rancher/hardened-build-base
Besides, it cherry picks the PR that enables dual-stack in Canal https://github.com/projectcalico/calico/pull/5313
Issue: https://github.com/rancher/rke2/issues/2342
Signed-off-by: manuelbuil <mbuil@suse.com>

Update to v3.20.3 and add dualStack support

---

Dockerfile
Makefile

This upgrade has three significant changes:
1 - Starting from v3.21, calico-node build requires bpf for amd64 architectures. Unfortunately, it is not possible to build bpf on alpine because libbpf-dev and libelf-dev packages do not exist there. That's why, we can't use our hardened-build-base image for calico-node build. Instead, we use goboring/golang image to build it, which is based on debian and includes those packages. As we are building statically, it does not matter where we build it. Note that the final binary is correctly verified with both `go-assert-static.sh` and `go-assert-boring.sh`
2 - Some extra lines are required in the calico-node build process. Basically, copying the bpf sources from `projectcalico/felix` and building the bpf code with `make -j 16 -C …

Upgrade to v3.21.2

---

Dockerfile

s390x build of felix only works with CGO_ENABLED=0
so we need a separate stage for s390x and amd64
This should fix the failed s390x build: https://drone-publish.rancher.io/rancher/image-build-calico/74/2/2

fix s390x build of calico-node

---

.github/dependabot.yml

This adds rancher/k3s to the PRs that dependabot generates.
This contributes to https://github.com/rancher/rke2/issues/4143.
I tested this by running [the dependabot cli](https://github.com/dependabot/cli) locally:
<details>
<summary>Test Scenario</summary>
```
input:
job:
package-manager: docker
allowed-updates:
- update-type: all
ignore-conditions:
- dependency-name: centos
source: dependabot_test
version-requirement: '>8'
source:
provider: github
repo: rancher/image-build-calico
directory: /
commit: 8424dc4baca42521f856ee67c70173731cf43d85
credentials-metadata:
- host: github.com
type: git_source
credentials:
- host: github.com
password: $LOCAL_GITHUB_ACCESS_TOKEN
type: git_source
username: x-access-token
output:
- type: update_dependency_list
expect:
data:
dependencies:
- name: …
```

Add dependabot reviewers

---

Dockerfile
Makefile
README.md

Update BCI image to the latest version with updated ipset to fix https://github.com/rancher/rke2/issues/4145
Update calico to version v3.25.1

Update BCI image and Calico version to 3.25.1

---

.drone.yml

This contributes to https://github.com/rancher/rke2/issues/4248
We want to exclude push events from dev or automated branches from CI.

Exclude dev branches from push events

---

.drone.yml

Drone yaml file is currently wrong for amd64, it clones the project and then runs the scan without running build, thus miserably failing: https://drone-publish.rancher.io/rancher/image-build-calico/139/3

Fix drone tags

---

Dockerfile
updatecli/updatecli.d/updatecalico.yaml
updatecli/updatecli.d/updatek3sroot.yaml
updatecli/updatecli.d/updateplugins.yaml
updatecli/values.yaml

This PR adapts Dockerfile a bit so that it is easy to change the versions with updateCLI.
It adds a policy for:
* Calico version
* cniplugins version
* k3sroot version

Use updatecli to update versions

---

updatecli/updatecli.d/updatebuildbase.yaml

This PR also searches for the go.mod version in the upstream project
Works: https://github.com/rancher/image-build-calico/pull/69

Use updatecli to update the base image in drone

---

Makefile
README.md
updatecli/updatecli.d/updatecalico.yaml

The tab in the Makefile is wrong because in that case it believes it is a recipe, so we get the error:
```
*** recipe commences before first target.  Stop.
```
As the Makefile is quite simple, and has been wrong for a long time, I think it is fine if we just remove the instruction. Then we tell updatecli to not update it anymore

Fix makefile

---

Dockerfile

From `v3.27.2` Calico moved the install binary outside from the cni. This fix builds the right install bin for calico-cni

Fixed Calico install binary moved from v3.27.2

---

.github/workflows/build.yml
.github/workflows/image-push.yml
Dockerfile
Makefile

This PR makes use of native runners provided by EIO to build the images.
It also builds the arch separately in image-push.yml to avoid the disk limitation of building both arch at once on a single builder.
The build pattern in image-push is based on https://docs.docker.com/build/ci/github-actions/multi-platform/.

Native build on dedicated runners

---

.github/workflows/image-push.yml

This PR adds ids to job steps and uses these to properly reference the outputs of the steps where needed (e.g. when exporting the digest of the image).

Use correct step names for digest export

---

updatecli/updatecli.d/updatebuildbase.yaml

Updatecli was failing because there was an old drone reference

Remove drone from updatecli

---

updatecli/updatecli.d/updatecalico.yaml

Now there are two TAGs in Makefile and we just want to change the one with the symbol ":"
Similar to: https://github.com/rancher/image-build-k8s-metrics-server/pull/53

Fix updatecli after GHA migration

---

Dockerfile

we remove centos7 because it is EOL and the mirror server has been shutdown

Use bci-base to build runit

---

updatecli/updatecli.d/updatecalico.yaml

This should ensures that there are no PRs "updating" to a lower minor release

set 'latest: true' in updatecli typefilter

---

.github/workflows/release.yml
Makefile

The prime repository prefix was overwritten, causing the built image to push twice to `docker.io`

Fixup push of release builds to the prime registry

---

.github/workflows/release.yml

`docker/metadata-action` step and `manifest-push` need a valid `REGISTRY_IMAGE` var set during the merge job
Fixup for: 4cd229ed92087b2126828e885b7dd02dcedd972b
Signed-off-by: Michael Fritch <mfritch@suse.com>

Set `REGISTRY_IMAGE` env during the merge job

---

.github/workflows/release.yml
Makefile

The output from the last run metadata job contains the digest
of the public container image, which causes the manifest-push
to fail when run against the prime container image
Fixes:
https://github.com/rancher/image-build-calico/actions/runs/12253052004/job/34186981992

Upload image metadata using `actions/upload-artifact`

---

.github/workflows/release.yml

`actions/upload-artifact` requires a unqiue name for each artifact to upload (e.g. `amd64`, `arm64` etc.)
Fixes:
https://github.com/rancher/image-build-calico/actions/runs/12272456160
```
Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

Use unique artifact names

---

updatecli/updatecli.d/updatecalico.yaml
updatecli/updatecli.d/updatek3sroot.yaml
updatecli/updatecli.d/updateplugins.yaml

Version bump PRs should use the semver instead of the latest tag
Issue: https://github.com/rancher/rke2/issues/6402

updatecli: use `semver` versionfilter

---

.github/workflows/release.yml

The "Inspect Image" step doesn't specify from which registry the image should be pulled from, so it defaults to `docker.io`, this PR prepends the Prime Registry to the image name:version.

[LTS] Fix inspect image CI step

---

Dockerfile
Makefile

This reverts commits:
- 1b8f5dfe27a24bfe31e62de78c496afab2ef631b
- 9f8627d61af3a88cd09f244a80bcc57ab19f11e0

Revert to calico `v3.29.1`

---

Dockerfile

Add the `-buildvcs=false` flag to omit version control information from the built binary images.
Issue: https://github.com/rancher/image-build-calico/issues/163

Prevent go1.24 from setting the main module's version
